### ISSUE TITLE
How do I view this repo as a site?

### ISSUE THREAD

**Issue by Tanz0rz** [JakeFanelli/CSGO-Nades#1]

**Comment by costaste** [comment]
https://jakefanelli.github.io/CSGO-Nades/pages/home.html

**Comment by lrtanner** [comment]
Thank you. This site is killer! I am sharing it with all of my friends. Very cool idea.

**Comment by JakeFanelli** [comment]
Sorry, never noticed the comments section. Glad someone helped you out! Thanks.
