### ISSUE TITLE
Do you want community contributions?

### ISSUE THREAD

**Issue by lrtanner** [JakeFanelli/CSGO-Nades#2]
If you specify a video format for people to save screen caps (dimensions, format, etc), we may be able to give you updated/new nades as time goes on. Thoughts?

**Comment by JakeFanelli** [comment]
Hey! Yeah I'm not too sure I want submissions. If someone sees a new smoke I'd be happy to receive said clip, learn it myself then add it to the site.

**Comment by skliffmueller** [comment]
I did something similar a few months ago. I want to take your map views and integrate it into my source using JS objects as configurations. https://github.com/skliffmueller/csgo-smokes You can see a running example here https://s3.amazonaws.com/shannons-csgo-smokes/index.html

**Comment by JakeFanelli** [comment]
Added in CSGO Nades 2.0
